[package]
name = "opendal_001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opendal = "0.42.0"
tokio = { version = "1.34.0", features = ["full"] }
